### ISSUE TITLE
Switching profiles

### ISSUE THREAD

**Issue by yanlin41020** [CroSafan/PetInfo#2]
With the mod, I switched profiles and I went into my skills menu because it wasn't detecting the taming level, and it crashed me. 
https://paste.ee/p/BX4d3

**Comment by CroSafan** [comment]
Does this only happen when the profile doesn't have taming unlocked? Meaning its only 'Taming' and not like 'Taming I'

**Comment by yanlin41020** [comment]
It's possible. Let me test that right now.

**Comment by yanlin41020** [comment]
Ah, yes. It only happens when the profile haven't earned any Taming experience, so it didn't have a number. I just tested it with my other profiles and alts. That does seem to be the case.
