### ISSUE TITLE
Doesn't detect pet when switching profiles

### ISSUE THREAD

**Issue by yanlin41020** [CroSafan/PetInfo#3]
Whenever I switch profiles, the mod just says "No pet selected! 0.0%" when I have a pet selected on the profile. It can be fixed by respawning the pet. Not sure how you'd fix this without using API.

**Comment by CroSafan** [comment]
That is intentional. You cannot get the pet without respawning it after profile switching, its the same with the taming level.

**Comment by yanlin41020** [comment]
Alright
