### ISSUE TITLE
Items' names show up instead of pet names and level

### ISSUE THREAD

**Issue by Dqmir** [CroSafan/PetInfo#5]
Whenever I select a pet while holding an item, the item's name shows up, for example, if I'm holding an Aspect of The Dragons sword, its name will appear.
![Minecraft](https://user-images.githubusercontent.com/69330473/89596981-15f09a00-d859-11ea-9429-3ec84dd283d5.gif)

**Comment by CroSafan** [comment]
Can you please provide what other mods do you have installed?

**Comment by Dqmir** [comment]
I use Skyblock Addons, Chat Triggers, Quickplay, Optifine, ArmorHUD, Patcher, Skypixel and Scrollable Tooltips
